paths:
  /products:
    get:
      summary: Obtiene todos los productos
      tags:
        - Productos
      responses:
        "200":
          description: Los productos fueron obtenidos correctamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo con la base de datos.
    post:
      summary: Crea un nuevo producto
      tags:
        - Productos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
            examples:
              example1:
                value:
                  title: "Agüita con gas"
                  description: "Bebida refrescante con sabor a soda"
                  code: 12345
                  price: 1.99
                  status: true
                  stock: 100
                  category: "gaseosa"
                  owner: "admin"
      responses:
        "201":
          description: Producto creado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo con la base de datos.

  /products/{pid}:
    get:
      summary: Obtiene un solo producto a partir de su ID
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto que se desea solicitar.
          schema:
            type: string
      responses:
        "200":
          description: Producto encontrado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo con la base de datos.
    put:
      summary: Actualiza un producto existente
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto que se desea actualizar.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        "200":
          description: Producto actualizado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo con la base de datos.
    delete:
      summary: Elimina un producto existente
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto que se desea eliminar.
          schema:
            type: string
      responses:
        "204":
          description: Producto eliminado exitosamente.
        "404":
          description: Producto no encontrado.
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo con la base de datos.
  
  /products/title/{title}:
    get:
      summary: Obtiene un solo producto a partir de su nombre
      tags:
        - Productos
      parameters:
        - name: title
          in: path
          required: true
          description: Title del producto que se desea solicitar.
          schema:
            type: string
      responses:
        "200":
          description: Producto encontrado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo con la base de datos.

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: Id autogenerado de Mongo
        title:
          type: string
          description: Título del producto
        description:
          type: string
          description: Descripción del producto
        code:
          type: number
          description: Código del producto
        price:
          type: number
          description: Precio del producto
        status:
          type: boolean
          description: Estado del producto (activo/inactivo)
        stock:
          type: number
          description: Cantidad en stock del producto
        category:
          type: string
          enum: ["gaseosa", "vino", "cerveza"]
          default: "gaseosa"
          description: Categoría del producto
        thumbnails:
          type: array
          items:
            type: string
          description: Imágenes del producto
        owner:
          type: string
          default: "admin"
          description: "Propietario del producto (por defecto: admin)"
      example:
        _id: "5f885be3b547644035f26353"
        title: "Agüita con gas"
        description: "Bebida refrescante con sabor a soda"
        code: 12345
        price: 1.99
        status: true
        stock: 100
        category: "gaseosa"
        owner: "admin"
